#!/usr/bin/python3
def factorize(n):
    """
    Factorize a number into a product of two smaller numbers.

    Parameters:
    n (int): The number to factorize.

    Returns:
    tuple: A tuple containing two factors of the number.
    """
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return i, n // i
    return 1, n


def main():
    """
    Main function to read numbers from a file and print their factorization.
    """
    with open('tests/test00', 'r') as file:
        numbers = [int(line.strip()) for line in file]

    for number in numbers:
        p, q = factorize(number)
        print(f'{number}={p}*{q}')


if __name__ == "__main__":
    main()
